#!/usr/bin/env python3
import argparse
import json
import os
import sys
from pathlib import Path

def common_geode_dirs():
    home = Path.home()
    candidates = [
        home / "GeometryDash",
        home / "GD",
        home / "geode",
        home / "games" / "GeometryDash",
        Path("/storage/emulated/0"),
        Path("/sdcard"),
        Path(".")
    ]

    # add common Android app dirs
    for base in ["/sdcard", "/storage/emulated/0"]:
        p = Path(base)
        if p.exists():
            for child in p.iterdir():
                if child.is_dir():
                    if "geometry" in child.name.lower() or "geode" in child.name.lower() or "gd" in child.name.lower():
                        candidates.append(child)

    seen = set()
    results = []
    for d in candidates:
        try:
            norm = str(d.resolve())
        except Exception:
            norm = str(d)
        if norm not in seen:
            seen.add(norm)
            results.append(d)
    return results

def find_geode_root(explicit=None):
    if explicit:
        p = Path(explicit)
        if p.exists():
            return p
        raise FileNotFoundError(f"Geode directory not found: {explicit}")

    for d in common_geode_dirs():
        if d.exists():
            name = d.name.lower()
            if "geode" in name or "geometry" in name or "gd" in name:
                return d
    return Path(".")  # fallback

def build_level(name, author="You", difficulty="Easy", length="Short"):
    spawn_x = 110
    spawn_y = 220

    objects = [
        {"id": 1, "type": "solid_block", "x": 80, "y": 280, "w": 150, "h": 30},
        {"id": 2, "type": "solid_block", "x": 260, "y": 260, "w": 140, "h": 30},
        {"id": 3, "type": "solid_block", "x": 430, "y": 240, "w": 140, "h": 30},
        {"id": 4, "type": "solid_block", "x": 610, "y": 220, "w": 140, "h": 30},
        {"id": 5, "type": "orb", "x": 340, "y": 180, "kind": "jump"},
        {"id": 6, "type": "orb", "x": 520, "y": 160, "kind": "jump"},
        {"id": 7, "type": "portal", "x": 760, "y": 170, "kind": "cube"},
    ]

    return {
        "level": {
            "name": name,
            "author": author,
            "difficulty": difficulty,
            "length": length,
            "version": "1.0",
            "spawn": {"x": spawn_x, "y": spawn_y},
            "background": {
                "theme": "default",
                "color_top": "#1E1B4B",
                "color_bottom": "#312E81"
            },
            "objects": objects
        }
    }

def create_level_files(output_root: Path, level_name: str, author: str, difficulty: str, length: str):
    out_dir = output_root / "generated_levels" / level_name
    out_dir.mkdir(parents=True, exist_ok=True)

    level_data = build_level(level_name, author, difficulty, length)

    json_path = out_dir / f"{level_name}.json"
    json_path.write_text(json.dumps(level_data, indent=2), encoding="utf-8")

    readme = out_dir / "README.txt"
    readme.write_text(
        "Generated by geode_level_maker.py\n"
        f"Level: {level_name}\n"
        f"Author: {author}\n"
        f"Difficulty: {difficulty}\n"
        f"Length: {length}\n\n"
        "This is a starter project file for a Geometry Dash/Geode level workflow.\n"
        "It is not a native GD binary file; it is a structured template you can adapt.\n",
        encoding="utf-8"
    )

    return out_dir, json_path

def main():
    parser = argparse.ArgumentParser(description="Create a starter Geometry Dash / Geode level project")
    parser.add_argument("--geode-dir", help="Path to your Geometry Dash or Geode folder")
    parser.add_argument("--name", default="MyLevel", help="Level name")
    parser.add_argument("--author", default="You", help="Level author")
    parser.add_argument("--difficulty", default="Easy", help="Level difficulty")
    parser.add_argument("--length", default="Short", help="Level length")
    args = parser.parse_args()

    try:
        geode_root = find_geode_root(args.geode_dir)
    except Exception as e:
        print(f"Error: {e}")
        return 1

    output_root = geode_root if geode_root.exists() else Path(".")
    out_dir, json_path = create_level_files(output_root, args.name, args.author, args.difficulty, args.length)

    print("Level created successfully.")
    print(f"Output folder: {out_dir}")
    print(f"JSON file: {json_path}")
    print()
    print("Next steps:")
    print("  1. Open the generated JSON file and tweak the object list.")
    print("  2. If you want a real Geode integration build, I can turn this into a proper Geode mod tool next.")
    print("  3. If you want me to target a specific file format, send me the Geode docs or folder structure you use.")

    return 0

if __name__ == "__main__":
    raise SystemExit(main())
